version: "3.8"
services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes: 
            - ./nginx/www:/usr/share/nginx/html
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
        networks:
            - lnmp-network
    php:
        image: php:7-fpm-alpine
        volumes:
            - ./nginx/www:/www
        networks:
            - lnmp-network
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=passw0rd
        networks:
            - lnmp-network
    redis:
        image: redis:6-alpine
        ports:
            - "6379:6379"
        volumes:
            - ./redis/data:/data
        networks:
            - lnmp-network
networks:
    lnmp-network: