FROM alpine:3.14

ARG APT="mirrors.ustc.edu.cn"
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    if [ "${APT}" != "" ] ; then \
    sed -i "s/dl-cdn.alpinelinux.org/${APT}/g" /etc/apk/repositories \
    ; fi

RUN apk update && \
    apk add --no-cache \
    php7-fpm \
    php7-pecl-redis php7-gd php7-zip php7-openssl php7-intl php7-dom php7-pdo_mysql
    
